### ISSUE TITLE
Add test to ensure everything inherits from Thing

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-models#24]
In the model everything at a minimum must inherit https://schema.org/Thing, or something else in schema.org or the OpenActive model

That is, each model file must either have a valid `subClassOf` or `derivedFrom`

**Comment by henryaddison** [comment]
@nickevansuk Should this apply to the FeedItem and FeedPage "models" as well?

**Comment by henryaddison** [comment]
@nickevansuk or @thill-odi I've put in place some tests that I think cover this issue in #38. However, one test is failing because Lease is `"derivedFrom": "#Thing"`. Based on other conversations I believe this should be `"subClassOf": "#Thing"` (and not `"derivedFrom": "https://schema.org/Thing"`) but then other tests fail because it's missing the Thing fields `url`, `name`, `sameAs`, `image`, `description` and `potentialAction` from its `inSpec` attribute. I'm not quite sure what the correct approach is here.

**Comment by nickevansuk** [comment]
Yes, it should be `"subClassOf": "#Thing"` - can we merge this then I can go fix the models so they all pass and check back here after I've finished QAing against your tests?

**Comment by henryaddison** [comment]
Yes, of course. It is now merged.
