### ISSUE TITLE
Add test to check against schema.org namespace

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-models#27]
1) Check all `sameAs` fields or fields that are in a model with `derivedFrom` to ensure they exist in schema.org.

Taking three examples from [here](https://github.com/openactive/data-models/blob/master/versions/2.x/models/Event.json):

> [`"fieldName": "genderRestriction",`](https://github.com/openactive/data-models/blob/master/versions/2.x/models/Event.json#L246)
`sameAs` is not schema.org, so ignore

> [`"fieldName": "eventStatus",`](https://github.com/openactive/data-models/blob/master/versions/2.x/models/Event.json#L237)
`sameAs` not specified, but [`derivedFrom`](https://github.com/openactive/data-models/blob/master/versions/2.x/models/Event.json#L3) is schema.org, so the existence of "https://schema.org/eventStatus" is implied. Check against schema.org to make sure this exists.

> [`"fieldName": "category",`](https://github.com/openactive/data-models/blob/master/versions/2.x/models/Event.json#L165)
`sameAs` is schema.org, so the existence of "https://schema.org/category" is stated. Check against schema.org to make sure this exists.

2) Check all `derivedFrom` referenced models exist in schema.org.

Taking one example from [here](https://github.com/openactive/data-models/blob/master/versions/2.x/models/Event.json):

> [`"derivedFrom": "https://schema.org/Event",`](https://github.com/openactive/data-models/blob/master/versions/2.x/models/Event.json#L3)
Check `derivedFrom` value `https://schema.org/Event` exists in schema.org

**Comment by henryaddison** [comment]
@nickevansuk Re: point 1, some `sameAs` fields point at properties in the https://openactive.io vocab rather than http://schema.org one (e.g. `activity` field on `Course` model). Does that mean they are invalid? Or do you want to check they exist in openactive.io? And if the latter, how? I'm now quite sure yet how the openactive properties are defined in order to check a particular one exists.

**Comment by nickevansuk** [comment]
The [model files](https://github.com/openactive/data-models/tree/master/versions/2.x) themselves define OpenActive.io vocab, the tests already check these for internal consistency.

I've edited the question above to make it clearer - what they're not doing right now is checking for external consistency (i.e. against schema.org)

**Comment by henryaddison** [comment]
I'm running into some issues with a few models relating to schema.org classes and properties that are still pending - see below for a list of affected models. The issue comes in because the way I am checking if any referenced schema.org classes or properties exist is to check they are included in the `@id`s of the entries in `@graph` of the latest JSONLD serialization (https://schema.org/version/latest/schema.jsonld) but pending entities aren't in there.

My questions are:
1. Do you mind the use of pending classes or properties?
2. Does that method of checking the schema.org data model make sense or do you per chance know a better way of querying the schema.org data model for the existence of a given model or property, particularly one which can have pending entries included?

* EventSeries: derived from http://schema.org/EventSeries class is pending.
* BookingService: http://schema.org/termsOfService property is pending.
* Organization: http://schema.org/termsOfService property is pending.
* Person: https://schema.org/jobTitle property is pending.

**Comment by henryaddison** [comment]
I've pushed some code to a PR which might give a bit more context to my comment above.

**Comment by nickevansuk** [comment]
Yep that's a great way to check against schema.org. https://github.com/openactive/data-model-validator already contains some similar logic.

This should help:
https://schema.org/version/latest/ext-pending.jsonld

OpenActive has decided to use pending props where appropriate (and they're referenced in the specs too, e.g. search "NOTE: Status of EventSeries" in https://www.openactive.io/modelling-opportunity-data/), so this is a consideration ongoing, and worth coding in

**Comment by henryaddison** [comment]
Thanks, Nick. I've updated the schema.org check to include the pending items too, so that's 4 fewer failing tests!
