### ISSUE TITLE
Add test to check that model references model, and that requiredType references one of a set of valid types

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-models#29]
Add test to check that model references model, and that requiredType references one of a set of valid types.

The latter line is invalid, as it is referencing a model as a type.

```
         "model": "ArrayOf#Terms",
         "requiredType":"ArrayOf#https://openactive.io/Terms",
```

**Comment by henryaddison** [comment]
@nickevansuk Just wondering if the Offer model needs to use http://purl.org/goodrelations/v1#PaymentMethod as a `requiredType` on the `acceptedPaymentMethod` field since it appears to be in schema.org too - https://schema.org/PaymentMethod.

I doubt it's a major issue but it's just another source of classes & properties to check against alongside openactive, skos and schema.org.

Here's the field:
```json
"acceptedPaymentMethod": {
         "fieldName": "acceptedPaymentMethod",
         "sameAs": "https://schema.org/acceptedPaymentMethod",
         "requiredType": "ArrayOf#http://purl.org/goodrelations/v1#PaymentMethod",
         "description": [
            "Indicates the offline payment methods accepted by this provider."
         ],
         "example": [
            "http://purl.org/goodrelations/v1#Cash",
            "http://purl.org/goodrelations/v1#PaymentMethodCreditCard"
         ]
      },
```
